Time Series Use-cases integrated with UI
AnalyticsCal/AnalyticsCal-Classroom pull request #40
Opened 2019-12-08 13:17 UTC by vishnu-dev

# What is this PR/ Why we need it?
Tine series UI Integration

# Does the commit involve changes to code / documentation?
(If both check both the boxes)
- [X] Code
  - [X] I have tested the entire code and it works fine :)
  - [ ] I have tested the entire code but there are bugs and I have reported them/ raised an issue for the same :|
  - [ ] No, I have not tested :(
- [ ] Documentation

## Concerned team/ people:
- [ ] Team 1
- [ ] Team 2
- [ ] Team 3
- [ ] Team 4
- [ ] Team 5
- [X] Team 6
- [X] Team 7
- [X] Team 8
- [ ] Team 9

2019-12-08 16:55 UTC, kn-neelalohitha requested changes
@vishnu-dev thanks for integrating! Please go through review comments and include these small changes also!
Or else everything is fine!

2019-12-08 16:55 UTC, kn-neelalohitha commented on test_tab.py
> +# from anova import main as anova_main
Please un-comment this line 43

2019-12-08 16:55 UTC, kn-neelalohitha commented on test_tab.py
> -import seaborn as sns
Please include this line as well 
```python
 import seaborn as sns
```
we use it for multiple linear regression

2019-12-08 16:55 UTC, kn-neelalohitha commented on test_tab.py
> +# from anova import main as anova_main
We still use anova_main [here](https://github.com/AnalyticsCal/AnalyticsCal-Classroom/blob/d54333b1a52a50fc5a1c2a59a694d58dd6178034/test_tab.py#L819)

2019-12-08 16:55 UTC, kn-neelalohitha commented on anova - Copy.py
> +# How to use..?
Rename this file `anova.py`

2019-12-08 16:55 UTC, kn-neelalohitha commented on anova.py
> +# 2. Pass y_list=y vaues, y_cap_list=y predected values, degree_of_freedom= number of parameters to class
Please rename this file as `anova_class.py`

2019-12-08 19:09 UTC, kn-neelalohitha commented
Requested changes are incorporated!
LGTM!
Thanks @vishnu-dev !!

2019-12-08 19:10 UTC, kn-neelalohitha approved these changes

2019-12-08 19:11 UTC, merged

2019-12-09 03:01 UTC, vishnu-dev commented
@kn-neelalohitha Thanks for fixing the conflicts.

2019-12-09 18:57 UTC, kn-neelalohitha commented
@vishnu-dev It was a pleasure working with u! And thank u for the feature!